fix bug of --context option and add --after, --before support
gabmontes/source-map-cli pull request #1
Opened 2017-06-27 11:35 UTC by sarike

When I use this tool, I found `--context` did not work as expected.

Because the value of `--context` was used as string.

So the result of https://github.com/gabmontes/source-map-cli/blob/master/lib/lineSlicer.js#L11 will be wrong.

Please accept and release a new package asap, thank you very much.

2017-07-04 02:16 UTC, gabmontes requested changes
@sarike thanks for pointing this out! Please remove the `yarn.lock` file so I can accept the PR, and publish a new version.

2017-07-05 02:26 UTC, sarike commented
@gabmontes `yarn.lock` has been removed.

2017-07-05 02:34 UTC, gabmontes approved these changes

2017-07-05 02:34 UTC, merged

2017-07-05 02:34 UTC, gabmontes commented
@sarike thanks! Publishing new version...